experiment:
  seed: 28
  num_epochs: 100

modalities:
  depth:
    model:
      resnet:
        class_name: ResNet
        from_module: depth
        args: []
        kwargs:
          batch_size: 32
          lr: 0.001
          sample_length: 31
          resnet_type: 34
          optimizer_name: "adam"
          metric_name: "accuracy"
      videonet:
        class_name: VideoNet
        from_module: depth
        args: [ ]
        kwargs:
          batch_size: 32
          lr: 0.001
          sample_length: 31
          model_type: "res"
          optimizer_name: "adam"
          metric_name: "accuracy"
    transforms:
      - class_name: DepthSampler
        from_module: depth_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 31
      - class_name: DepthResize
        from_module: depth_transforms
        transform_name: resizing
        in_test: true
        kwargs:
          height: 100 #50
          width: 120 #70
      - class_name: ToRGB
        from_module: depth_transforms
        transform_name: RGBconvert
        in_test: true

