experiment:
  seed: 28
  num_epochs: 100

modalities:
  rgb:
    model:
      resnet:
        class_name: ResNet
        from_module: video
        args: []
        kwargs:
          batch_size: 32
          lr: 0.001
          sample_length: 31
          resnet_type: 34
          optimizer_name: "adam"
          metric_name: "accuracy"
      videonet:
        class_name: VideoNet
        from_module: video
        args: [ ]
        kwargs:
          batch_size: 8
          lr: 0.001
          sample_length: 31
          model_type: "res"
          optimizer_name: "adam"
          metric_name: "accuracy"
    transforms:
      - class_name: VideoSampler
        from_module: video_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 31
      - class_name: VideoResize
        from_module: video_transforms
        transform_name: resizing
        in_test: true
        kwargs:
          crop: true
          height: 50 #187 130
          width: 35 #154 100
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [ -1, 0, 1, 2 ]
      - class_name: ToFloat
        transform_name: to_float
        from_module: general_transforms
        in_test: true

