#place holder since we dont have augmentations yet
jittering:
  apply: false
  parameters:
    sigma: 0.1
  probability: 1
crop_and_resize:
  apply: false
  parameters:
    min_p: 0.8
    max_p: 0.9
    size: 50
  probability: 0.75
scaling:
  apply: false
  parameters:
    dimensions: 3
    min_p: 0.7
    max_p: 1.2
  probability: 0.75
rotation:
  apply: false
  parameters:
    dimensions: 3
    start: -10
    end: 10
    step: 2
    anchor_joint: 2
  probability: 0.75
shear:
  apply: false
  parameters:
    dimensions: 3
    beta: 0.2
  probability: 0.75