program: ssl_training_mm.py
method: bayes
project: sweep-mm_ssl-inertial-skeleton-mmact
entity: self-supervised-mmhar
metric:
  name: test_f1-score
  goal: maximize
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--dataset"
  - "mmact"
  - "--data_path"
  - "/home/data/multimodal_har_datasets/mmact_new"
  - "--modalities"
  - "inertial skeleton"
  - "--models"
  - "transformer cooccurrence"
  - "--experiment_config_path"
  - "configs/VICReg/vicreg_inertial_skeleton_mmact.yaml"
  - "--augmentations_path"
  - "configs/inertial_augmentations/augmentations_mmact.yaml  configs/skeleton_augmentations/augmentations_mmact.yaml"
  - "--online-eval"
  - "--num-workers"
  - "8"
  - "--framework"
  - "vicreg"
#  - "--no_ckpt"
  - "--sweep"
parameters:
  # General configs
  num_epochs_ssl:
    values: [100]

  # SSL configs (will overwrite kwargs in ssl model definition)
  ssl.batch_size:
    values: [128, 256]
  ssl.sim_coeff:
    values: [2, 5, 10, 20]
  ssl.std_coeff:
    values: [20, 25, 30, 40]
  ssl.cov_coeff:
    values: [1, 3, 5]
  ssl.lr:
    values: [0.001, 0.0005]